"""Optional Buenos Aires geographic preset. Not a global default of the engine."""

from __future__ import annotations

from leadfinder.errors import ConfigError

CABA = "Ciudad Autonoma de Buenos Aires"

CABA_NEIGHBORHOODS: tuple[str, ...] = (
    "Palermo, Ciudad Autonoma de Buenos Aires",
    "Recoleta, Ciudad Autonoma de Buenos Aires",
    "Retiro, Ciudad Autonoma de Buenos Aires",
    "Microcentro, Ciudad Autonoma de Buenos Aires",
    "Puerto Madero, Ciudad Autonoma de Buenos Aires",
    "San Telmo, Ciudad Autonoma de Buenos Aires",
    "Belgrano, Ciudad Autonoma de Buenos Aires",
    "Almagro, Ciudad Autonoma de Buenos Aires",
    "Caballito, Ciudad Autonoma de Buenos Aires",
    "Villa Crespo, Ciudad Autonoma de Buenos Aires",
)

COAST: tuple[str, ...] = (
    "Mar del Plata",
    "Chapadmalal",
    "Miramar",
    "Mar del Sur",
    "Villa Gesell",
    "Pinamar",
    "Carilo",
    "Valeria del Mar",
    "Ostende",
    "San Clemente del Tuyu",
    "Las Toninas",
    "Santa Teresita",
    "Mar del Tuyu",
    "Costa del Este",
    "Aguas Verdes",
    "Lucila del Mar",
    "San Bernardo",
    "Mar de Ajo",
    "Nueva Atlantis",
    "Necochea",
    "Quequen",
    "Monte Hermoso",
    "Pehuen Co",
    "Claromeco",
    "Reta",
    "Orense",
    "Mar Chiquita",
)

AMBA: tuple[str, ...] = (
    "La Plata",
    "Tigre",
    "Pilar",
    "Escobar",
    "San Isidro",
    "Vicente Lopez",
    "Moron",
    "Ramos Mejia",
    "San Justo",
    "Quilmes",
    "Avellaneda",
    "Lanus",
    "Lomas de Zamora",
    "Ezeiza",
    "Campana",
    "Zarate",
    "San Miguel",
    "Moreno",
    "Merlo",
    "Berazategui",
    "Florencio Varela",
    "Almirante Brown",
)

INTERIOR: tuple[str, ...] = (
    "Bahia Blanca",
    "Tandil",
    "Sierra de la Ventana",
    "Lujan",
    "San Antonio de Areco",
    "San Pedro",
    "San Nicolas de los Arroyos",
    "Pergamino",
    "Junin",
    "Olavarria",
    "Azul",
    "Chascomus",
    "Mercedes",
    "Chivilcoy",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Dolores",
    "Bragado",
    "Balcarce",
    "Nueve de Julio",
    "Veinticinco de Mayo",
    "Lincoln",
    "Chacabuco",
    "Saladillo",
    "Bolivar",
    "Pehuajo",
    "Coronel Suarez",
    "Coronel Pringles",
    "Coronel Dorrego",
    "Lobos",
)

BALANCED_EXTRAS: tuple[str, ...] = (
    "Batan",
    "Sierra de los Padres",
    "La Matanza",
    "Jose C. Paz",
    "Malvinas Argentinas",
    "Hurlingham",
    "Ituzaingo",
    "Tres de Febrero",
    "Esteban Echeverria",
    "Canuelas",
    "Ensenada",
    "Berisso",
    "Baradero",
    "Ramallo",
    "Arrecifes",
    "Salto",
    "Colon",
    "Rojas",
    "General Villegas",
    "Carlos Casares",
    "Daireaux",
    "Tapalque",
    "Laprida",
    "Benito Juarez",
    "Ayacucho",
    "Maipu",
    "Patagones",
    "Carmen de Patagones",
)

PARTIDOS: tuple[str, ...] = (
    "Adolfo Alsina",
    "Adolfo Gonzales Chaves",
    "Alberti",
    "Almirante Brown",
    "Arrecifes",
    "Avellaneda",
    "Ayacucho",
    "Azul",
    "Bahia Blanca",
    "Balcarce",
    "Baradero",
    "Benito Juarez",
    "Berazategui",
    "Berisso",
    "Bolivar",
    "Bragado",
    "Brandsen",
    "Campana",
    "Canuelas",
    "Capitan Sarmiento",
    "Carlos Casares",
    "Carlos Tejedor",
    "Carmen de Areco",
    "Castelli",
    "Chacabuco",
    "Chascomus",
    "Chivilcoy",
    "Colon",
    "Coronel Dorrego",
    "Coronel Pringles",
    "Coronel Rosales",
    "Coronel Suarez",
    "Daireaux",
    "Dolores",
    "Ensenada",
    "Escobar",
    "Esteban Echeverria",
    "Exaltacion de la Cruz",
    "Ezeiza",
    "Florencio Varela",
    "Florentino Ameghino",
    "General Alvarado",
    "General Alvear",
    "General Arenales",
    "General Belgrano",
    "General Guido",
    "General Juan Madariaga",
    "General La Madrid",
    "General Las Heras",
    "General Lavalle",
    "General Paz",
    "General Pinto",
    "General Pueyrredon",
    "General Rodriguez",
    "General San Martin",
    "General Viamonte",
    "General Villegas",
    "Guamini",
    "Hipolito Yrigoyen",
    "Hurlingham",
    "Ituzaingo",
    "Jose C. Paz",
    "Junin",
    "La Costa",
    "La Matanza",
    "La Plata",
    "Lanus",
    "Laprida",
    "Las Flores",
    "Leandro N. Alem",
    "Lezama",
    "Lincoln",
    "Loberia",
    "Lobos",
    "Lomas de Zamora",
    "Lujan",
    "Magdalena",
    "Maipu",
    "Malvinas Argentinas",
    "Mar Chiquita",
    "Marcos Paz",
    "Mercedes",
    "Merlo",
    "Monte",
    "Monte Hermoso",
    "Moreno",
    "Moron",
    "Navarro",
    "Necochea",
    "Nueve de Julio",
    "Olavarria",
    "Patagones",
    "Pehuajo",
    "Pellegrini",
    "Pergamino",
    "Pila",
    "Pilar",
    "Pinamar",
    "Presidente Peron",
    "Puan",
    "Punta Indio",
    "Quilmes",
    "Ramallo",
    "Rauch",
    "Rivadavia",
    "Rojas",
    "Roque Perez",
    "Saavedra",
    "Saladillo",
    "Salliquelo",
    "Salto",
    "San Andres de Giles",
    "San Antonio de Areco",
    "San Cayetano",
    "San Fernando",
    "San Isidro",
    "San Miguel",
    "San Nicolas",
    "San Pedro",
    "San Vicente",
    "Suipacha",
    "Tandil",
    "Tapalque",
    "Tigre",
    "Tordillo",
    "Tornquist",
    "Trenque Lauquen",
    "Tres Arroyos",
    "Tres de Febrero",
    "Tres Lomas",
    "Veinticinco de Mayo",
    "Vicente Lopez",
    "Villa Gesell",
    "Villarino",
    "Zarate",
)

CITY_EXTRAS: tuple[str, ...] = (
    "Mar del Plata",
    "Batan",
    "Sierra de los Padres",
    "Chapadmalal",
    "Carilo",
    "Valeria del Mar",
    "Ostende",
    "San Clemente del Tuyu",
    "Las Toninas",
    "Santa Teresita",
    "Mar del Tuyu",
    "Costa del Este",
    "Aguas Verdes",
    "Lucila del Mar",
    "San Bernardo",
    "Mar de Ajo",
    "Nueva Atlantis",
    "Quequen",
    "Miramar",
    "Mar del Sur",
    "Pehuen Co",
    "Claromeco",
    "Reta",
    "Orense",
    "Sierra de la Ventana",
    "San Nicolas de los Arroyos",
    "Carmen de Patagones",
)


def _unique(values: tuple[str, ...] | list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for raw in values:
        item = raw.strip()
        key = " ".join(item.lower().split())
        if not item or key in seen:
            continue
        seen.add(key)
        result.append(item)
    return result


def buenos_aires_locations(coverage: str) -> list[str]:
    if coverage == "budget":
        return _unique((CABA, *CABA_NEIGHBORHOODS, *COAST, *AMBA, *INTERIOR))
    if coverage == "balanced":
        return _unique((CABA, *CABA_NEIGHBORHOODS, *COAST, *AMBA, *INTERIOR, *BALANCED_EXTRAS))
    if coverage == "full":
        return _unique(
            (
                CABA,
                *CABA_NEIGHBORHOODS,
                *PARTIDOS,
                *CITY_EXTRAS,
                *COAST,
                *AMBA,
                *INTERIOR,
                *BALANCED_EXTRAS,
            )
        )
    raise ConfigError(f"Unknown coverage '{coverage}'. Choose budget, balanced, or full.")
